'use server';

/**
 * @fileOverview Automatically tags images based on their content using AI.
 *
 * - imageAutoTagging - A function that handles the image auto-tagging process.
 * - ImageAutoTaggingInput - The input type for the imageAutoTagging function.
 * - ImageAutoTaggingOutput - The return type for the imageAutoTagging function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImageAutoTaggingInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo to tag, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'      
    ),
});
export type ImageAutoTaggingInput = z.infer<typeof ImageAutoTaggingInputSchema>;

const ImageAutoTaggingOutputSchema = z.object({
  tags: z.array(z.string()).describe('The tags generated by the AI.'),
});
export type ImageAutoTaggingOutput = z.infer<typeof ImageAutoTaggingOutputSchema>;

export async function imageAutoTagging(input: ImageAutoTaggingInput): Promise<ImageAutoTaggingOutput> {
  return imageAutoTaggingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'imageAutoTaggingPrompt',
  input: {schema: ImageAutoTaggingInputSchema},
  output: {schema: ImageAutoTaggingOutputSchema},
  prompt: `You are an AI assistant that analyzes images and generates relevant tags.

  Analyze the image and generate tags appropriate to the image.  These tags should be a single word or short phrase.
  The tags must be relevant to the image.

  Image: {{media url=photoDataUri}}`,
});

const imageAutoTaggingFlow = ai.defineFlow(
  {
    name: 'imageAutoTaggingFlow',
    inputSchema: ImageAutoTaggingInputSchema,
    outputSchema: ImageAutoTaggingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
